from paragami.version import __version__

from paragami.base_patterns import PatternDict
from paragami.numeric_array_patterns import NumericArrayPattern
from paragami.pdmatrix_patterns import PDMatrixPattern
from paragami.function_patterns import FlattenedFunction
